language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository

script:
  - "./gradlew publishApkDebug"

before_install:
- ruby -v
- chmod +x gradlew
- gem update --system
- gem install fir-cli
