 language: android
    sudo: false
    git:
      depth: 3 #将git depth设置相对小的值,加快构建速度
    jdk:
    - oraclejdk8 #lambda表达式支持,如果工程中使用了rxJava等类库时添加
    android:
      components:
      - tools
      - build-tools-23.0.3
      - android-23
      - extra-android-m2repository
      - extra-android-support
    script:
    - "./gradlew assembleRelease"
    before_install:
    - chmod +x gradlew
    - gem install fir-cli #安装fir命令行客户端
    deploy:
      provider: releases
      api_key:
        secure: SHA256:3CanRLnSjzJnj+BkgAMe0ieSTj1TMS77Ex4dC+7xuPw “1141179268@qq.com”
      file: appild/outputs/apk/app-release.apk
      skip_cleanup: true
      on:
        repo: lianshangyangguang/GwellDemo2
    after_deploy:
    - fir login 8f68d31a204da27bfcc3747fa11dcbb6 #fir账号的Token
    - fir me #打印身份信息,验证是否登录成功
    - fir p appild/outputs/apk/app-release.apk #自动发布应用至fir内测平台
